---
- name: Install Wazuh Manager + OpenSearch + Dashboard on Debian 12 LXC
  hosts: wazuh_node
  become: yes

  vars:
    opensearch_admin_password: "admin123"  # arbitrary placeholder to satisfy startup check

  tasks:

    - name: Set hostname to 'wazuh'
      hostname:
        name: wazuh

    - name: Ensure /etc/hosts has hostname mapping
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+'
        line: '127.0.1.1   wazuh'
        create: yes

    - name: Install base dependencies
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - software-properties-common
          - lsb-release
        update_cache: yes
        state: present

    # ----------------- Repositories -----------------

    - name: Add Wazuh GPG key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add Wazuh repository
      apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        filename: wazuh
        state: present

    - name: Add OpenSearch GPG key
      apt_key:
        url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
        state: present

    - name: Add OpenSearch APT repo
      apt_repository:
        repo: "deb https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main"
        filename: opensearch
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    # ----------------- Preemptively write OpenSearch config -----------------

    - name: Ensure OpenSearch config directory exists
      file:
        path: /etc/opensearch
        state: directory

    - name: Pre-write OpenSearch config (before package install)
      copy:
        dest: /etc/opensearch/opensearch.yml
        content: |
          cluster.name: wazuh-cluster
          node.name: wazuh
          network.host: 0.0.0.0
          discovery.seed_hosts: ["127.0.0.1"]
          cluster.initial_master_nodes: ["wazuh"]
          plugins.security.disabled: true
        owner: root
        group: root
        mode: '0644'

    # ----------------- Install OpenSearch and immediately disable post-install script -----------------

    - name: Install OpenSearch
      apt:
        name: opensearch
        state: present

    - name: Remove demo config script to prevent forced security
      file:
        path: /usr/share/opensearch/plugins/opensearch-security/tools/install_demo_configuration.sh
        state: absent

    # ----------------- Start OpenSearch -----------------

    - name: Enable and start OpenSearch
      systemd:
        name: opensearch
        enabled: yes
        state: started

    - name: Wait for OpenSearch to respond
      uri:
        url: http://localhost:9200
        method: GET
        status_code: 200
        return_content: yes
      register: opensearch_response
      retries: 10
      delay: 10
      until: opensearch_response.status == 200

    # ----------------- Install Wazuh -----------------

    - name: Install wazuh-manager
      apt:
        name: wazuh-manager
        state: present

    - name: Enable and start wazuh-manager
      systemd:
        name: wazuh-manager
        enabled: yes
        state: started

    - name: Install wazuh-dashboard
      apt:
        name: wazuh-dashboard
        state: present

    - name: Enable and start wazuh-dashboard
      systemd:
        name: wazuh-dashboard
        enabled: yes
        state: started
