---
- name: Install Docker and Docker Compose on Debian 12 LXC
  hosts: netbox
  become: true

  vars:
    docker_apt_repo: "https://download.docker.com/linux/debian"
    docker_gpg_key_url: "https://download.docker.com/linux/debian/gpg"
    docker_release: "bullseye"  # 👈 Use bullseye for compatibility

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: "{{ docker_gpg_key_url }}"
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker APT repository for bullseye
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] {{ docker_apt_repo }} {{ docker_release }} stable"
        state: present
        filename: docker

    - name: Force APT cache update
      command: apt-get update

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user | default('root') }}"
        groups: docker
        append: yes
