---
- name: Install Docker and Docker Compose on Debian 12 LXC
  hosts: netbox
  become: true

  vars:
    docker_apt_repo: "https://download.docker.com/linux/debian"
    docker_gpg_key_url: "https://download.docker.com/linux/debian/gpg"
    docker_release: "bullseye"  # Use bullseye repo for compatibility with Debian 12
    docker_key_path: "/etc/apt/keyrings/docker.gpg"

  tasks:
    - name: Ensure base system packages are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create keyring directory if it doesn't exist
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key (binary format)
      shell: |
        curl -fsSL {{ docker_gpg_key_url }} | gpg --dearmor -o {{ docker_key_path }}
      args:
        creates: "{{ docker_key_path }}"

    - name: Ensure Docker GPG key is readable
      stat:
        path: "{{ docker_key_path }}"
      register: docker_gpg_key

    - name: Fail if Docker GPG key is not present
      fail:
        msg: "Docker GPG key is missing or not installed correctly!"
      when: not docker_gpg_key.stat.exists

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by={{ docker_key_path }}] {{ docker_apt_repo }} {{ docker_release }} stable"
        state: present
        filename: docker

    - name: Force update APT cache
      apt:
        update_cache: yes

    - name: Install Docker engine and components
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user | default('root') }}"
        groups: docker
        append: yes
