---
- name: Install Docker and Docker Compose on Debian 12 LXC
  hosts: all
  become: true

  vars:
    docker_apt_repo: "https://download.docker.com/linux/debian"
    docker_gpg_key_url: "https://download.docker.com/linux/debian/gpg"
    docker_release: "bullseye"

  tasks:
    - name: Ensure required base packages are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key using apt-key (legacy workaround)
      ansible.builtin.shell: |
        curl -fsSL {{ docker_gpg_key_url }} | apt-key add -
      changed_when: false

    - name: Add Docker APT repository (without signed-by)
      apt_repository:
        repo: "deb [arch=amd64] {{ docker_apt_repo }} {{ docker_release }} stable"
        state: present
        filename: docker

    - name: Update APT cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker service is enabled and started
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user | default('root') }}"
        groups: docker
        append: yes
