---
- name: Add Docker repository to Debian 12 LXC
  hosts: tester
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker official GPG key
      ansible.builtin.shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable"
        create: yes

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker packages (optional)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
