---
- name: Install CrowdSec on Debian LXC
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - curl
          - gnupg2
        state: present

    - name: Add CrowdSec repository key
      shell: curl -fsSL https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash

    - name: Install CrowdSec
      apt:
        name: crowdsec
        state: present

    - name: Enable and start CrowdSec service
      systemd:
        name: crowdsec
        state: started
        enabled: yes
