---
- name: Deploy Wazuh Manager + Dashboard on Debian 12 (Single Node)
  hosts: wazuh
  become: yes
  vars:
    wazuh_repo_url: "https://packages.wazuh.com/4.x/apt/"
    wazuh_gpg_key_url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
    wazuh_version: "4.7.3"

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base dependencies
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - lsb-release
          - software-properties-common
        state: present

    - name: Add Wazuh GPG key
      apt_key:
        url: "{{ wazuh_gpg_key_url }}"
        state: present

    - name: Add Wazuh repository
      apt_repository:
        repo: "deb {{ wazuh_repo_url }} stable main"
        filename: "wazuh"
        state: present

    - name: Update apt cache again
      apt:
        update_cache: yes

    - name: Install Wazuh Manager
      apt:
        name: wazuh-manager
        state: present

    - name: Enable and start Wazuh Manager
      systemd:
        name: wazuh-manager
        enabled: yes
        state: started

    - name: Install OpenSearch
      apt:
        name: opensearch
        state: present

    - name: Configure OpenSearch network access
      lineinfile:
        path: /etc/opensearch/opensearch.yml
        regexp: '^network\.host:'
        line: 'network.host: 0.0.0.0'
        create: yes

    - name: Enable and start OpenSearch
      systemd:
        name: opensearch
        enabled: yes
        state: started

    - name: Wait for OpenSearch to respond
      uri:
        url: http://localhost:9200
        method: GET
        return_content: yes
        status_code: 200
      register: result
      retries: 10
      delay: 10
      until: result.status == 200

    - name: Install Wazuh Dashboard
      apt:
        name: "wazuh-dashboard={{ wazuh_version }}"
        state: present

    - name: Enable and start Wazuh Dashboard
      systemd:
        name: wazuh-dashboard
        enabled: yes
        state: started

    - name: Open ports via UFW (Optional, only if UFW is installed)
      block:
        - name: Install UFW
          apt:
            name: ufw
            state: present

        - name: Allow Wazuh Manager & Dashboard ports
          ufw:
            rule: allow
            port: "{{ item }}"
          loop:
            - 1514/udp
            - 1515/tcp
            - 5601/tcp

        - name: Enable UFW
          ufw:
            state: enabled
            policy: allow
