- name: Install Docker Compose on Debian 12 Proxmox LXC
  hosts: all
  remote_user: "{{ ansible_user | default('eljefe') }}"
  become: yes
  tasks:
    - name: Install required dependencies
      apt:
        name:
          - curl
          - jq
        state: present
        update_cache: yes

    - name: Get the latest Docker Compose version
      shell: |
        curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name
      register: compose_version

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_version.stdout }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: compose_check
      changed_when: false

    - name: Display installed version
      debug:
        msg: "Docker Compose version installed: {{ compose_check.stdout }}"
