---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name: ["ca-certificates", "curl", "gnupg"]
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Verify Docker Installation
      command: docker --version
      register: docker_version_output

    - name: Print Docker Version
      debug:
        msg: "Docker installed successfully: {{ docker_version_output.stdout }}"

    - name: Verify Docker Compose Installation
      command: docker-compose --version
      register: docker_compose_version_output

    - name: Print Docker Compose Version
      debug:
        msg: "Docker Compose installed successfully: {{ docker_compose_version_output.stdout }}"
