---
- name: Deploy Wazuh Manager + OpenSearch + Dashboard on Debian 12
  hosts: wazuh
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required base packages
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - lsb-release
          - software-properties-common
        state: present

    ## -- Add Wazuh Repo --

    - name: Add Wazuh GPG key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add Wazuh APT repository
      apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        filename: wazuh
        state: present

    ## -- Add OpenSearch Repo --

    - name: Add OpenSearch GPG key
      apt_key:
        url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
        state: present

    - name: Add OpenSearch APT repository
      apt_repository:
        repo: "deb https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main"
        filename: opensearch
        state: present

    - name: Update apt cache after adding repos
      apt:
        update_cache: yes

    ## -- Install and Start Wazuh Manager --

    - name: Install Wazuh Manager
      apt:
        name: wazuh-manager
        state: present

    - name: Enable and start Wazuh Manager
      systemd:
        name: wazuh-manager
        enabled: yes
        state: started

    ## -- Install and Start OpenSearch --

    - name: Install OpenSearch
      apt:
        name: opensearch
        state: present

    - name: Configure OpenSearch to bind to all interfaces
      lineinfile:
        path: /etc/opensearch/opensearch.yml
        regexp: '^network\.host:'
        line: 'network.host: 0.0.0.0'
        create: yes

    - name: Enable and start OpenSearch
      systemd:
        name: opensearch
        enabled: yes
        state: started

    - name: Wait for OpenSearch to respond
      uri:
        url: http://localhost:9200
        method: GET
        return_content: yes
        status_code: 200
      register: opensearch_check
      retries: 10
      delay: 10
      until: opensearch_check.status == 200

    ## -- Install and Start Wazuh Dashboard --

    - name: Install Wazuh Dashboard
      apt:
        name: wazuh-dashboard
        state: present

    - name: Enable and start Wazuh Dashboard
      systemd:
        name: wazuh-dashboard
        enabled: yes
        state: started
