---
- name: Install and register Wazuh agent on Debian 12
  hosts: wazuh_agents
  become: yes
  vars:
    wazuh_manager_ip: "192.168.1.49"
    wazuh_repo_key: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
    wazuh_repo_file: "/etc/apt/sources.list.d/wazuh.list"
    wazuh_repo_url: "https://packages.wazuh.com/4.x/apt/"
    wazuh_agent_package: "wazuh-agent"

  tasks:

    - name: Add Wazuh GPG key
      apt_key:
        url: "{{ wazuh_repo_key }}"
        state: present

    - name: Add Wazuh APT repository
      apt_repository:
        repo: "deb {{ wazuh_repo_url }} stable main"
        filename: "wazuh"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Wazuh agent
      apt:
        name: "{{ wazuh_agent_package }}"
        state: present

    - name: Disable unattended upgrades (Debian default)
      systemd:
        name: unattended-upgrades
        enabled: no
        state: stopped

    - name: Ensure manager IP is correctly set in ossec.conf
      xml:
        path: /var/ossec/etc/ossec.conf
        xpath: /ossec_config/client/server/address
        value: "{{ wazuh_manager_ip }}"
        state: present
        pretty_print: yes
      notify: restart wazuh agent

  handlers:
    - name: restart wazuh agent
      systemd:
        name: wazuh-agent
        state: restarted
