---
- name: Install and register Wazuh Agent on Linux
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name: 
          - curl
          - gnupg
          - apt-transport-https
        state: present

    - name: Add the Wazuh GPG key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add the Wazuh repository
      apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present
        filename: wazuh

    - name: Install the Wazuh agent
      apt:
        name: wazuh-agent
        state: present

    - name: Enable and start the Wazuh agent service
      systemd:
        name: wazuh-agent
        enabled: yes
        state: started

    - name: Wait for wazuh-agent config file to be available
      wait_for:
        path: /var/ossec/etc/ossec.conf
        timeout: 30

    - name: Register agent with manager IP using XML module
      xml:
        path: /var/ossec/etc/ossec.conf
        xpath: /ossec_config/client/server-ip
        value: "192.168.1.49"
        state: present
      notify:
        - Restart Wazuh Agent

  handlers:
    - name: Restart Wazuh Agent
      systemd:
        name: wazuh-agent
        state: restarted

    - name: Display the Wazuh agent service status
      command: systemctl status wazuh-agent --no-pager
      register: agent_status
      changed_when: false
      run_once: true
      notify:
        - Debug Wazuh Agent Status

  handlers:
    - name: Debug Wazuh Agent Status
      debug:
        msg: "{{ agent_status.stdout_lines }}"