---
- name: Install & register Wazuh Agent on Debian-based Linux
  hosts: all
  become: true

  vars:
    wazuh_manager_ip: "192.168.1.49"

  tasks:
    - name: Install apt prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Wazuh GPG key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add Wazuh APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.wazuh.com/4.x/apt/ stable main"
        filename: wazuh
        state: present
        update_cache: yes

    - name: Install Wazuh Agent
      apt:
        name: wazuh-agent
        state: present

    - name: Wait for wazuh.conf to exist
      wait_for:
        path: /var/ossec/etc/ossec.conf
        timeout: 30

    - name: Point agent at the manager IP
      xml:
        path: /var/ossec/etc/ossec.conf
        xpath: /ossec_config/client/server-ip
        value: "{{ wazuh_manager_ip }}"
        state: present
      notify: Restart wazuh-agent

    - name: Ensure wazuh-agent is enabled & running
      systemd:
        name: wazuh-agent
        enabled: yes
        state: started

  handlers:
    - name: Restart wazuh-agent
      systemd:
        name: wazuh-agent
        state: restarted